### ISSUE TITLE
Support for DynamicImage

### ISSUE THREAD

**Issue by WalrusSoup** [jaehl/blockhash#2]
Using the [latest image crate](https://docs.rs/image/latest/image/) and running into an issue..

Im super new to rust and just started picking it up, so I apologize if it's fine and I'm simply not sure what I am doing.

```
the trait bound `DynamicImage: Image` is not satisfied
the trait `Image` is not implemented for `DynamicImage`
```

It looks like `GenericImageView` items were implemented for `DynamicImage` has what it needs but I cant seem to get it to work. I then attempted to use Blockhash256::from(), but it appears the definitions only allow a fixed size vector.

Can you point me in the right direction? Thanks!

**Comment by jaehl** [comment]
Hi, the problem is that you are using version 0.24 of `image`, but `blockhash` depends on version 0.23 (and the two are incompatible).

I've just released version 0.4.0 of `blockhash`, which depends on version 0.24 of `image`; if you update to that it should start working.

**Comment by WalrusSoup** [comment]
Seems like it's still missing something. Maybe I am doing something wrong on my end? I pulled 0.4.0 and still see the same result.

Cargo.toml
```toml
[dependencies]
image = "0.24.1"
blockhash = "0.4.0"
```

Source:
```rs
  let image = image::open("/tmp/1.jpg").unwrap();
  let image_hash = blockhash256(&image);
```

Cargo Check:
```
15  |   let image_hash = blockhash256(&image);
    |                    ------------ ^^^^^^ the trait `Image` is not implemented for `DynamicImage`
    |                    |
    |                    required by a bound introduced by this call

```

**Comment by jaehl** [comment]
You'll also need to enable the `image` feature flag, like so:

```toml
[dependencies]
image = "0.24.1"
blockhash = { version = "0.4.0", features = ["image"] }
```

**Comment by WalrusSoup** [comment]
It works! Thanks so much! I appreciate your help with this.
